### PR TITLE
Initial release

### PR DESCRIPTION
**Pull request by mikekinsman**
pulling sptramer's initial release into a test branch to see it build

### CODE REVIEW

**Comment by mikekinsman** [comment]
@sptramer I know you didn't want to merge your go stuff into master, but I wanted to make sure it was building so I pulled it into the 'mikefromsteve' branch on the repo.  See https://review.docs.microsoft.com/en-us/go/azure/index?branch=mikefromsteve if you want a snapshot.  Ping me too if you have questions or need to chat or need to tell me to back off :)

**Comment by sptramer** [comment]
No worries, this PR will be tagged DO NOT MERGE and should be deleted if you're satisfied with the result.

**Comment by mikekinsman** [comment]
@sptramer  I'm trying to stay agnostic of content decisions.   My point in doing this is you're not getting your content built out with your existing PR.  Why are you tagging yours as "do not merge" ?  My PR isn't going to master so it wont affect anything.

**Comment by sptramer** [comment]
@mikekinsman Mine is tagged as DNM because it should not be merged until it's offically ready to go live. If this PR is not going to be merged, it should be deleted. My content is still being built and staged so I'm not sure why this is necessary.

If it won't be merged, please close it.

**Comment by mikekinsman** [comment]
@sptramer all I'm saying is it's not up to me to merge it.  Not because I don't like you guys, but because I want you guys to own the content decisions.  You're on the admins team for Azure Go so you can merge it if you choose to.

**Pull request merged**
